title: "Biblioteca Digital - Abdiel"
description: "Documentación y portafolio personal"
baseurl: ""
url: "https://abdielgv162.github.io"

# Usar el tema que YA VIENE con Jekyll
theme: minima

# Información personal
github_username: abdielgv162
email: "tu-email@ejemplo.com"  # Opcional

# Configuración Jekyll
markdown: kramdown
permalink: pretty

# Plugins que ya vienen incluidos
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración adicional
author: "Abdiel"